#!/usr/bin/env python
from geneinfo.hgnc_geneinfo import main as geneinfo_index
from hmdb.drugbank import main as drugbank_index
from hmdb.index import main as hmdb_index

"""
Command line interface for nosql-biosets project index/query scripts

Project scripts are not easily reachable when a package installation made
for example using pip

This script is added to user PATH when a package installation made
and could be used to call functions in the index/query scripts
"""

import argh
from argh import arg

datasets_help = '''
Dataset to index: only HGNC, HMDB and DrugBank datasets are supported,
support for more datasets to be implemented
'''


@arg('dataset', help=datasets_help)
@arg('db', help='MongoDB or Elasticsearch')
@arg('infile', help='Input file to index')
@arg('--database', help='MongoDB database name')
@arg('--collection', help='MongoDB collection name, if undefined'
                          ' default names in index scripts are used')
def index(dataset, db, infile, database='biosets', collection=None):
    """
    Index given input file of the dataset selected
    """
    print("%s   %s  %s" % (db, infile, database))
    if dataset == 'hgnc':
        geneinfo_index(db, infile, database)
    elif dataset == 'hmdb':
        hmdb_index(infile, database, collection, db)
    elif dataset == 'drugbank':
        drugbank_index(infile, db, database)


if __name__ == "__main__":
    argh.dispatch_commands([
        index
    ])
